### ISSUE TITLE
Criar Página 'Sobre'

### ISSUE THREAD

**Issue by pvguerra** [nobreDaniel/pixelup#2]
Incluir todos os membros da equipe Pixel Up e links para redes sociais.

**Comment by nobreDaniel** [comment]
Tava pensando da pag sobre ser já na página inicial. Tipo já mostra o que é o projeto os componentes principais e um formulário básico de contato

**Comment by pvguerra** [comment]
Na página inicial vou colocar umas chamadas para o projeto e apoio também, na sobre vai ficar mais detalhado.

**Comment by pvguerra** [comment]
> Tava pensando da pag sobre ser já na página inicial. Tipo já mostra o que é o projeto os componentes principais e um formulário básico de contato

Na página inicial vou colocar umas chamadas para o projeto e apoio também, na sobre vai ficar mais detalhado.

**Comment by pvguerra** [comment]
> Tava pensando da pag sobre ser já na página inicial. Tipo já mostra o que é o projeto os componentes principais e um formulário básico de contato

O form de contato vai ficar na inicial sim 👍
